//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36366
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportLocalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal English() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReportLocalization.English", typeof(English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aahara.
        /// </summary>
        internal static string Aahara {
            get {
                return ResourceManager.GetString("Aahara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aahara Shakthi.
        /// </summary>
        internal static string Aahara_Shakthi {
            get {
                return ResourceManager.GetString("Aahara_Shakthi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abortions.
        /// </summary>
        internal static string Abortions {
            get {
                return ResourceManager.GetString("Abortions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 1.
        /// </summary>
        internal static string Address_Line_1 {
            get {
                return ResourceManager.GetString("Address_Line_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 2.
        /// </summary>
        internal static string Address_Line_2 {
            get {
                return ResourceManager.GetString("Address_Line_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alcohol.
        /// </summary>
        internal static string Alcohol {
            get {
                return ResourceManager.GetString("Alcohol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Centers.
        /// </summary>
        internal static string All_Centers {
            get {
                return ResourceManager.GetString("All_Centers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allergy.
        /// </summary>
        internal static string Allergy {
            get {
                return ResourceManager.GetString("Allergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analam.
        /// </summary>
        internal static string Analam {
            get {
                return ResourceManager.GetString("Analam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anubandha Dosha.
        /// </summary>
        internal static string Anubandha_Dosha {
            get {
                return ResourceManager.GetString("Anubandha_Dosha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appetite/Agn.
        /// </summary>
        internal static string Appetite_Agn {
            get {
                return ResourceManager.GetString("Appetite_Agn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment &amp; Plan of Care.
        /// </summary>
        internal static string Assessment_Plan_of_Care {
            get {
                return ResourceManager.GetString("Assessment_Plan_of_Care", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUHID No.
        /// </summary>
        internal static string AUHID_No {
            get {
                return ResourceManager.GetString("AUHID_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayurvedic Assessment.
        /// </summary>
        internal static string Ayurvedic_Assessment {
            get {
                return ResourceManager.GetString("Ayurvedic_Assessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bala.
        /// </summary>
        internal static string Bala {
            get {
                return ResourceManager.GetString("Bala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch No.
        /// </summary>
        internal static string Batch_No {
            get {
                return ResourceManager.GetString("Batch_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilirubin.
        /// </summary>
        internal static string Bilirubin {
            get {
                return ResourceManager.GetString("Bilirubin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Amount.
        /// </summary>
        internal static string Bill_Amount {
            get {
                return ResourceManager.GetString("Bill_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Date.
        /// </summary>
        internal static string Bill_Date {
            get {
                return ResourceManager.GetString("Bill_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill No.
        /// </summary>
        internal static string Bill_No {
            get {
                return ResourceManager.GetString("Bill_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Information.
        /// </summary>
        internal static string Billing_Information {
            get {
                return ResourceManager.GetString("Billing_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood.
        /// </summary>
        internal static string Blood {
            get {
                return ResourceManager.GetString("Blood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Group.
        /// </summary>
        internal static string Blood_Group {
            get {
                return ResourceManager.GetString("Blood_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Pressure.
        /// </summary>
        internal static string Blood_Pressure {
            get {
                return ResourceManager.GetString("Blood_Pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMI.
        /// </summary>
        internal static string BMI {
            get {
                return ResourceManager.GetString("BMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breast.
        /// </summary>
        internal static string Breast {
            get {
                return ResourceManager.GetString("Breast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardiology.
        /// </summary>
        internal static string Cardiology {
            get {
                return ResourceManager.GetString("Cardiology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Type.
        /// </summary>
        internal static string Case_Type {
            get {
                return ResourceManager.GetString("Case_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Name.
        /// </summary>
        internal static string CENTER_NAME {
            get {
                return ResourceManager.GetString("CENTER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerebellar Signs.
        /// </summary>
        internal static string Cerebellar_Signs {
            get {
                return ResourceManager.GetString("Cerebellar_Signs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chew Tobacco.
        /// </summary>
        internal static string Chew_Tobacco {
            get {
                return ResourceManager.GetString("Chew_Tobacco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief Complaints.
        /// </summary>
        internal static string Chief_Complaints {
            get {
                return ResourceManager.GetString("Chief_Complaints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cholesterol.
        /// </summary>
        internal static string Cholesterol {
            get {
                return ResourceManager.GetString("Cholesterol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinic.
        /// </summary>
        internal static string Clinic {
            get {
                return ResourceManager.GetString("Clinic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comorbid Conditions.
        /// </summary>
        internal static string Comorbid_Conditions {
            get {
                return ResourceManager.GetString("Comorbid_Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consolidated OP Billing Report.
        /// </summary>
        internal static string Consolidated_OP_Billing_Report {
            get {
                return ResourceManager.GetString("Consolidated_OP_Billing_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultation Details .
        /// </summary>
        internal static string Consultation_Details {
            get {
                return ResourceManager.GetString("Consultation_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact No.
        /// </summary>
        internal static string Contact_No {
            get {
                return ResourceManager.GetString("Contact_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        internal static string Date_of_Birth {
            get {
                return ResourceManager.GetString("Date_of_Birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Time.
        /// </summary>
        internal static string Date_Time {
            get {
                return ResourceManager.GetString("Date_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dermatology.
        /// </summary>
        internal static string Dermatology {
            get {
                return ResourceManager.GetString("Dermatology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desha.
        /// </summary>
        internal static string Desha {
            get {
                return ResourceManager.GetString("Desha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialastic.
        /// </summary>
        internal static string Dialastic {
            get {
                return ResourceManager.GetString("Dialastic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diet.
        /// </summary>
        internal static string Diet {
            get {
                return ResourceManager.GetString("Diet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount%.
        /// </summary>
        internal static string Discount_ {
            get {
                return ResourceManager.GetString("Discount_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Amount.
        /// </summary>
        internal static string Discount_Amount {
            get {
                return ResourceManager.GetString("Discount_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Amount.
        /// </summary>
        internal static string Discount_Amount1 {
            get {
                return ResourceManager.GetString("Discount_Amount1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Amount.
        /// </summary>
        internal static string Discount_Amount2 {
            get {
                return ResourceManager.GetString("Discount_Amount2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        internal static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you currently drink  coffe and/or tea?.
        /// </summary>
        internal static string Do_you_currently_drink_coffe_and_or_tea {
            get {
                return ResourceManager.GetString("Do_you_currently_drink_coffe_and_or_tea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you exercise?.
        /// </summary>
        internal static string Do_you_exercise {
            get {
                return ResourceManager.GetString("Do_you_exercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOCTOR.
        /// </summary>
        internal static string DOCTOR {
            get {
                return ResourceManager.GetString("DOCTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor Consultation.
        /// </summary>
        internal static string Doctor_Consultation {
            get {
                return ResourceManager.GetString("Doctor_Consultation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor Name.
        /// </summary>
        internal static string Doctor_Name {
            get {
                return ResourceManager.GetString("Doctor_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dooshya.
        /// </summary>
        internal static string Dooshya {
            get {
                return ResourceManager.GetString("Dooshya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosha.
        /// </summary>
        internal static string Dosha {
            get {
                return ResourceManager.GetString("Dosha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug History.
        /// </summary>
        internal static string Drug_History {
            get {
                return ResourceManager.GetString("Drug_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drugs Prescription.
        /// </summary>
        internal static string Drugs_Prescription {
            get {
                return ResourceManager.GetString("Drugs_Prescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Amount.
        /// </summary>
        internal static string Due_Amount {
            get {
                return ResourceManager.GetString("Due_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Paid Amount.
        /// </summary>
        internal static string Due_Paid_Amount {
            get {
                return ResourceManager.GetString("Due_Paid_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECG.
        /// </summary>
        internal static string ECG {
            get {
                return ResourceManager.GetString("ECG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        internal static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to END OF REPORT.
        /// </summary>
        internal static string END_OF_REPORT {
            get {
                return ResourceManager.GetString("END_OF_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endocrinology.
        /// </summary>
        internal static string Endocrinology {
            get {
                return ResourceManager.GetString("Endocrinology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENT.
        /// </summary>
        internal static string ENT {
            get {
                return ResourceManager.GetString("ENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examination of the Cranial Nerves.
        /// </summary>
        internal static string Examination_of_the_Cranial_Nerves {
            get {
                return ResourceManager.GetString("Examination_of_the_Cranial_Nerves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examination of the Higher Functions.
        /// </summary>
        internal static string Examination_of_the_Higher_Functions {
            get {
                return ResourceManager.GetString("Examination_of_the_Higher_Functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examination of the Motor Nerves.
        /// </summary>
        internal static string Examination_of_the_Motor_Nerves {
            get {
                return ResourceManager.GetString("Examination_of_the_Motor_Nerves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examination of the Reflexes.
        /// </summary>
        internal static string Examination_of_the_Reflexes {
            get {
                return ResourceManager.GetString("Examination_of_the_Reflexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examination of the Sensory Nerves.
        /// </summary>
        internal static string Examination_of_the_Sensory_Nerves {
            get {
                return ResourceManager.GetString("Examination_of_the_Sensory_Nerves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Date.
        /// </summary>
        internal static string Expiry_Date {
            get {
                return ResourceManager.GetString("Expiry_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family History.
        /// </summary>
        internal static string Family_History {
            get {
                return ResourceManager.GetString("Family_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Planning Methods.
        /// </summary>
        internal static string Family_Planning_Methods {
            get {
                return ResourceManager.GetString("Family_Planning_Methods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEV1.
        /// </summary>
        internal static string FEV1 {
            get {
                return ResourceManager.GetString("FEV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FHR.
        /// </summary>
        internal static string FHR {
            get {
                return ResourceManager.GetString("FHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Assessment.
        /// </summary>
        internal static string Final_Assessment {
            get {
                return ResourceManager.GetString("Final_Assessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Diagnosis.
        /// </summary>
        internal static string Final_Diagnosis {
            get {
                return ResourceManager.GetString("Final_Diagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Up.
        /// </summary>
        internal static string Follow_Up {
            get {
                return ResourceManager.GetString("Follow_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for.
        /// </summary>
        internal static string for_ {
            get {
                return ResourceManager.GetString("for_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Quantity.
        /// </summary>
        internal static string Free_Quantity {
            get {
                return ResourceManager.GetString("Free_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FVC.
        /// </summary>
        internal static string FVC {
            get {
                return ResourceManager.GetString("FVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gastrointestinal System.
        /// </summary>
        internal static string Gastrointestinal_System {
            get {
                return ResourceManager.GetString("Gastrointestinal_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Assessment.
        /// </summary>
        internal static string General_Assessment {
            get {
                return ResourceManager.GetString("General_Assessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Instructions.
        /// </summary>
        internal static string General_Instructions {
            get {
                return ResourceManager.GetString("General_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Medcine.
        /// </summary>
        internal static string General_Medicine {
            get {
                return ResourceManager.GetString("General_Medicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genito-Urinary.
        /// </summary>
        internal static string Genito_Urinary {
            get {
                return ResourceManager.GetString("Genito_Urinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genitoreproductive.
        /// </summary>
        internal static string Genitoreproductive {
            get {
                return ResourceManager.GetString("Genitoreproductive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glucose.
        /// </summary>
        internal static string Glucose {
            get {
                return ResourceManager.GetString("Glucose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GP-Assessment.
        /// </summary>
        internal static string GP_Assessment {
            get {
                return ResourceManager.GetString("GP_Assessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravida.
        /// </summary>
        internal static string Gravida {
            get {
                return ResourceManager.GetString("Gravida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross Amount.
        /// </summary>
        internal static string Gross_Amount {
            get {
                return ResourceManager.GetString("Gross_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HDL Cholesterol.
        /// </summary>
        internal static string HDL_Cholesterol {
            get {
                return ResourceManager.GetString("HDL_Cholesterol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head.
        /// </summary>
        internal static string Head {
            get {
                return ResourceManager.GetString("Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height(cm).
        /// </summary>
        internal static string Height_cm {
            get {
                return ResourceManager.GetString("Height_cm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hematologic/Lymphatic System.
        /// </summary>
        internal static string Hematologic_Lymphatic_System {
            get {
                return ResourceManager.GetString("Hematologic_Lymphatic_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hematology.
        /// </summary>
        internal static string Hematology {
            get {
                return ResourceManager.GetString("Hematology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History of Present Illness.
        /// </summary>
        internal static string History_of_Present_Illness {
            get {
                return ResourceManager.GetString("History_of_Present_Illness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Phone.
        /// </summary>
        internal static string Home_Phone {
            get {
                return ResourceManager.GetString("Home_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How Many Drinks Per Week ?.
        /// </summary>
        internal static string How_Many_Drinks_Per_Week {
            get {
                return ResourceManager.GetString("How_Many_Drinks_Per_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How Many Packs Per Day?.
        /// </summary>
        internal static string How_Many_Packs_Per_Day {
            get {
                return ResourceManager.GetString("How_Many_Packs_Per_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydration.
        /// </summary>
        internal static string Hydration {
            get {
                return ResourceManager.GetString("Hydration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If is how Many cups Per Day?.
        /// </summary>
        internal static string If_is_how_Many_cups_Per_Day {
            get {
                return ResourceManager.GetString("If_is_how_Many_cups_Per_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If quit  when did you quit.
        /// </summary>
        internal static string If_quit_when_did_you_quit {
            get {
                return ResourceManager.GetString("If_quit_when_did_you_quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If quit  when did you quit.
        /// </summary>
        internal static string If_quit_when_did_you_quit1 {
            get {
                return ResourceManager.GetString("If_quit_when_did_you_quit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If quit  when did you quit.
        /// </summary>
        internal static string If_quit_when_did_you_quit2 {
            get {
                return ResourceManager.GetString("If_quit_when_did_you_quit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If yes.
        /// </summary>
        internal static string If_yes {
            get {
                return ResourceManager.GetString("If_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immunisation History.
        /// </summary>
        internal static string Immunisation_History {
            get {
                return ResourceManager.GetString("Immunisation_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infectious Diseases.
        /// </summary>
        internal static string Infectious_Diseases {
            get {
                return ResourceManager.GetString("Infectious_Diseases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigation Group.
        /// </summary>
        internal static string Investigation_Group {
            get {
                return ResourceManager.GetString("Investigation_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigation Name.
        /// </summary>
        internal static string Investigation_Name {
            get {
                return ResourceManager.GetString("Investigation_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigations Advised.
        /// </summary>
        internal static string Investigations_Advised {
            get {
                return ResourceManager.GetString("Investigations_Advised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kala.
        /// </summary>
        internal static string Kala {
            get {
                return ResourceManager.GetString("Kala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ketones.
        /// </summary>
        internal static string Ketones {
            get {
                return ResourceManager.GetString("Ketones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LDL Cholesterol.
        /// </summary>
        internal static string LDL_Cholesterol {
            get {
                return ResourceManager.GetString("LDL_Cholesterol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leucocytes.
        /// </summary>
        internal static string Leucocytes {
            get {
                return ResourceManager.GetString("Leucocytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living.
        /// </summary>
        internal static string Living {
            get {
                return ResourceManager.GetString("Living", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LMP.
        /// </summary>
        internal static string LMP {
            get {
                return ResourceManager.GetString("LMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lymphatic.
        /// </summary>
        internal static string Lymphatic {
            get {
                return ResourceManager.GetString("Lymphatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lymphatic System.
        /// </summary>
        internal static string Lymphatic_System {
            get {
                return ResourceManager.GetString("Lymphatic_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malaria Test.
        /// </summary>
        internal static string Malaria_Test {
            get {
                return ResourceManager.GetString("Malaria_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAP.
        /// </summary>
        internal static string MAP {
            get {
                return ResourceManager.GetString("MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marital Status.
        /// </summary>
        internal static string Marital_Status {
            get {
                return ResourceManager.GetString("Marital_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Name.
        /// </summary>
        internal static string Material_Name {
            get {
                return ResourceManager.GetString("Material_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Level.
        /// </summary>
        internal static string Maximum_Level {
            get {
                return ResourceManager.GetString("Maximum_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meningeal Signs.
        /// </summary>
        internal static string Meningeal_Signs {
            get {
                return ResourceManager.GetString("Meningeal_Signs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menstrual History.
        /// </summary>
        internal static string Menstrual_History {
            get {
                return ResourceManager.GetString("Menstrual_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Level.
        /// </summary>
        internal static string Minimum_Level {
            get {
                return ResourceManager.GetString("Minimum_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile 1.
        /// </summary>
        internal static string Mobile_1 {
            get {
                return ResourceManager.GetString("Mobile_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile 2.
        /// </summary>
        internal static string Mobile_2 {
            get {
                return ResourceManager.GetString("Mobile_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musulo-Skeletal.
        /// </summary>
        internal static string Musculo_Skeletal {
            get {
                return ResourceManager.GetString("Musculo_Skeletal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musculoskeletal System.
        /// </summary>
        internal static string Musculoskeletal_System {
            get {
                return ResourceManager.GetString("Musculoskeletal_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nails.
        /// </summary>
        internal static string Nails {
            get {
                return ResourceManager.GetString("Nails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National ID.
        /// </summary>
        internal static string National_ID {
            get {
                return ResourceManager.GetString("National_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        internal static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Amount.
        /// </summary>
        internal static string Net_Amount {
            get {
                return ResourceManager.GetString("Net_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Amount.
        /// </summary>
        internal static string Net_Amount1 {
            get {
                return ResourceManager.GetString("Net_Amount1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuro-Psychiatric.
        /// </summary>
        internal static string Neuro_Psychiatric {
            get {
                return ResourceManager.GetString("Neuro_Psychiatric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neurologic System.
        /// </summary>
        internal static string Neurologic_System {
            get {
                return ResourceManager.GetString("Neurologic_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next To Kin Details.
        /// </summary>
        internal static string Next_To_Kin_Details {
            get {
                return ResourceManager.GetString("Next_To_Kin_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nitrates.
        /// </summary>
        internal static string Nitrates {
            get {
                return ResourceManager.GetString("Nitrates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Reference Range.
        /// </summary>
        internal static string Normal_Reference_Range {
            get {
                return ResourceManager.GetString("Normal_Reference_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Reference Range.
        /// </summary>
        internal static string Normal_Reference_Range1 {
            get {
                return ResourceManager.GetString("Normal_Reference_Range1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obestetrics/Gynecology.
        /// </summary>
        internal static string Obestetrics_Gynecology {
            get {
                return ResourceManager.GetString("Obestetrics_Gynecology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obstetric History.
        /// </summary>
        internal static string Obstetric_History {
            get {
                return ResourceManager.GetString("Obstetric_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupation.
        /// </summary>
        internal static string Occupation {
            get {
                return ResourceManager.GetString("Occupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupational History.
        /// </summary>
        internal static string Occupational_History {
            get {
                return ResourceManager.GetString("Occupational_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        internal static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Phone.
        /// </summary>
        internal static string Office_Phone {
            get {
                return ResourceManager.GetString("Office_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OP Consult Note.
        /// </summary>
        internal static string OP_Consult_Note {
            get {
                return ResourceManager.GetString("OP_Consult_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OP Due Collection.
        /// </summary>
        internal static string OP_Due_Collection {
            get {
                return ResourceManager.GetString("OP_Due_Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ophthamology.
        /// </summary>
        internal static string Ophthamology {
            get {
                return ResourceManager.GetString("Ophthamology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orthopedic.
        /// </summary>
        internal static string Orthopedic {
            get {
                return ResourceManager.GetString("Orthopedic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Recommendations.
        /// </summary>
        internal static string Other_Recommendations {
            get {
                return ResourceManager.GetString("Other_Recommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        internal static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        internal static string Others1 {
            get {
                return ResourceManager.GetString("Others1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out Patient Consultation Note.
        /// </summary>
        internal static string Out_Patient_Consultation_Note {
            get {
                return ResourceManager.GetString("Out_Patient_Consultation_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages.
        /// </summary>
        internal static string Packages {
            get {
                return ResourceManager.GetString("Packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Amount.
        /// </summary>
        internal static string Paid_Amount {
            get {
                return ResourceManager.GetString("Paid_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pain Score.
        /// </summary>
        internal static string Pain_Score {
            get {
                return ResourceManager.GetString("Pain_Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para.
        /// </summary>
        internal static string Para {
            get {
                return ResourceManager.GetString("Para", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past Medical History.
        /// </summary>
        internal static string Past_Medical_History {
            get {
                return ResourceManager.GetString("Past_Medical_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past Surgical History.
        /// </summary>
        internal static string Past_Surgical_History {
            get {
                return ResourceManager.GetString("Past_Surgical_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Address.
        /// </summary>
        internal static string Patient_Address {
            get {
                return ResourceManager.GetString("Patient_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Category.
        /// </summary>
        internal static string Patient_Category {
            get {
                return ResourceManager.GetString("Patient_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Category.
        /// </summary>
        internal static string Patient_Category1 {
            get {
                return ResourceManager.GetString("Patient_Category1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Name.
        /// </summary>
        internal static string Patient_Name {
            get {
                return ResourceManager.GetString("Patient_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Pay Amount.
        /// </summary>
        internal static string Patient_Pay_Amount {
            get {
                return ResourceManager.GetString("Patient_Pay_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Registration Infomation.
        /// </summary>
        internal static string Patient_Registration_Infomation {
            get {
                return ResourceManager.GetString("Patient_Registration_Infomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Type.
        /// </summary>
        internal static string Patient_Type {
            get {
                return ResourceManager.GetString("Patient_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Type.
        /// </summary>
        internal static string Patient_Type1 {
            get {
                return ResourceManager.GetString("Patient_Type1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payable Amount.
        /// </summary>
        internal static string Payable_Amount {
            get {
                return ResourceManager.GetString("Payable_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Type.
        /// </summary>
        internal static string Payment_Type {
            get {
                return ResourceManager.GetString("Payment_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Type.
        /// </summary>
        internal static string Payment_Type1 {
            get {
                return ResourceManager.GetString("Payment_Type1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pediatrics.
        /// </summary>
        internal static string Pediatrics {
            get {
                return ResourceManager.GetString("Pediatrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PEF.
        /// </summary>
        internal static string PEF {
            get {
                return ResourceManager.GetString("PEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PH.
        /// </summary>
        internal static string PH {
            get {
                return ResourceManager.GetString("PH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacist.
        /// </summary>
        internal static string Pharmacist {
            get {
                return ResourceManager.GetString("Pharmacist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy No.
        /// </summary>
        internal static string Pharmacy_No {
            get {
                return ResourceManager.GetString("Pharmacy_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Examination.
        /// </summary>
        internal static string Physical_Examination {
            get {
                return ResourceManager.GetString("Physical_Examination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Stock.
        /// </summary>
        internal static string Physical_Stock {
            get {
                return ResourceManager.GetString("Physical_Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Code.
        /// </summary>
        internal static string Pin_Code {
            get {
                return ResourceManager.GetString("Pin_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Of Care.
        /// </summary>
        internal static string Plan_Of_Care {
            get {
                return ResourceManager.GetString("Plan_Of_Care", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan of Care.
        /// </summary>
        internal static string Plan_of_Care1 {
            get {
                return ResourceManager.GetString("Plan_of_Care1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posture/Weight.
        /// </summary>
        internal static string Posture_Weight {
            get {
                return ResourceManager.GetString("Posture_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prakruthi.
        /// </summary>
        internal static string Prakruthi {
            get {
                return ResourceManager.GetString("Prakruthi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregnancy Test.
        /// </summary>
        internal static string Pregnancy_Test {
            get {
                return ResourceManager.GetString("Pregnancy_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescribed On.
        /// </summary>
        internal static string Prescribed_On {
            get {
                return ResourceManager.GetString("Prescribed_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printed on.
        /// </summary>
        internal static string Printed_on {
            get {
                return ResourceManager.GetString("Printed_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedures Advised.
        /// </summary>
        internal static string Procedures_Advised {
            get {
                return ResourceManager.GetString("Procedures_Advised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protein.
        /// </summary>
        internal static string Protein {
            get {
                return ResourceManager.GetString("Protein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provisional Assessment.
        /// </summary>
        internal static string Provisional_Assessment {
            get {
                return ResourceManager.GetString("Provisional_Assessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provisional Diagnosis.
        /// </summary>
        internal static string Provisional_Diagnosis {
            get {
                return ResourceManager.GetString("Provisional_Diagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psychiatric.
        /// </summary>
        internal static string Psychiatric {
            get {
                return ResourceManager.GetString("Psychiatric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse/ Heart Rate.
        /// </summary>
        internal static string Pulse_Heart_Rate {
            get {
                return ResourceManager.GetString("Pulse_Heart_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse/Nadi.
        /// </summary>
        internal static string Pulse_Nadi {
            get {
                return ResourceManager.GetString("Pulse_Nadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Price.
        /// </summary>
        internal static string Purchase_Price {
            get {
                return ResourceManager.GetString("Purchase_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Unit.
        /// </summary>
        internal static string Purchase_Unit {
            get {
                return ResourceManager.GetString("Purchase_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QOH .
        /// </summary>
        internal static string QOH {
            get {
                return ResourceManager.GetString("QOH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QTY.
        /// </summary>
        internal static string QTY {
            get {
                return ResourceManager.GetString("QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        internal static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Per Unit.
        /// </summary>
        internal static string Rate_Per_Unit {
            get {
                return ResourceManager.GetString("Rate_Per_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratio.
        /// </summary>
        internal static string Ratio {
            get {
                return ResourceManager.GetString("Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectum.
        /// </summary>
        internal static string Rectum {
            get {
                return ResourceManager.GetString("Rectum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectum.
        /// </summary>
        internal static string Rectum1 {
            get {
                return ResourceManager.GetString("Rectum1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referal Doctor.
        /// </summary>
        internal static string Referal_Doctor {
            get {
                return ResourceManager.GetString("Referal_Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Sheet No.
        /// </summary>
        internal static string Reference_Sheet_No {
            get {
                return ResourceManager.GetString("Reference_Sheet_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship.
        /// </summary>
        internal static string Relationship {
            get {
                return ResourceManager.GetString("Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religion.
        /// </summary>
        internal static string Religion {
            get {
                return ResourceManager.GetString("Religion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        internal static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respiratory.
        /// </summary>
        internal static string Respiratory {
            get {
                return ResourceManager.GetString("Respiratory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respiratory System.
        /// </summary>
        internal static string Respiratory_System {
            get {
                return ResourceManager.GetString("Respiratory_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Date.
        /// </summary>
        internal static string Result_Date {
            get {
                return ResourceManager.GetString("Result_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result No.
        /// </summary>
        internal static string Result_No {
            get {
                return ResourceManager.GetString("Result_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string Result1 {
            get {
                return ResourceManager.GetString("Result1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rheumatology.
        /// </summary>
        internal static string Rheumatology {
            get {
                return ResourceManager.GetString("Rheumatology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roga (Disease) Avastha.
        /// </summary>
        internal static string Roga_Disease_Avastha {
            get {
                return ResourceManager.GetString("Roga_Disease_Avastha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roga Pariksha.
        /// </summary>
        internal static string Roga_Pariksha {
            get {
                return ResourceManager.GetString("Roga_Pariksha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROL.
        /// </summary>
        internal static string ROL {
            get {
                return ResourceManager.GetString("ROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROLE_DESC.
        /// </summary>
        internal static string ROLE_DESC {
            get {
                return ResourceManager.GetString("ROLE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Unit.
        /// </summary>
        internal static string Sale_Unit {
            get {
                return ResourceManager.GetString("Sale_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample No.
        /// </summary>
        internal static string Sample_No {
            get {
                return ResourceManager.GetString("Sample_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satwa.
        /// </summary>
        internal static string Satwa {
            get {
                return ResourceManager.GetString("Satwa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Amount.
        /// </summary>
        internal static string Service_Amount {
            get {
                return ResourceManager.GetString("Service_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Amount.
        /// </summary>
        internal static string Service_Amount1 {
            get {
                return ResourceManager.GetString("Service_Amount1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Name.
        /// </summary>
        internal static string Service_Name {
            get {
                return ResourceManager.GetString("Service_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVICE_NAME.
        /// </summary>
        internal static string SERVICE_NAME1 {
            get {
                return ResourceManager.GetString("SERVICE_NAME1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVICESUBGRP_NAME.
        /// </summary>
        internal static string SERVICESUBGRP_NAME {
            get {
                return ResourceManager.GetString("SERVICESUBGRP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sl.No.
        /// </summary>
        internal static string Sl_No {
            get {
                return ResourceManager.GetString("Sl_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep/Nidra.
        /// </summary>
        internal static string Sleep_Nidra {
            get {
                return ResourceManager.GetString("Sleep_Nidra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoke Cigarettes.
        /// </summary>
        internal static string Smoke_Cigarettes {
            get {
                return ResourceManager.GetString("Smoke_Cigarettes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoking.
        /// </summary>
        internal static string Smoking {
            get {
                return ResourceManager.GetString("Smoking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social History.
        /// </summary>
        internal static string Social_History {
            get {
                return ResourceManager.GetString("Social_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socioeconomic Status.
        /// </summary>
        internal static string Socioeconomic_Status {
            get {
                return ResourceManager.GetString("Socioeconomic_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific Gravity.
        /// </summary>
        internal static string Specific_Gravity {
            get {
                return ResourceManager.GetString("Specific_Gravity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spine.
        /// </summary>
        internal static string Spine {
            get {
                return ResourceManager.GetString("Spine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spine.
        /// </summary>
        internal static string Spine1 {
            get {
                return ResourceManager.GetString("Spine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spirometry.
        /// </summary>
        internal static string Spirometry {
            get {
                return ResourceManager.GetString("Spirometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spo2.
        /// </summary>
        internal static string Spo2 {
            get {
                return ResourceManager.GetString("Spo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Difference.
        /// </summary>
        internal static string Stock_Difference {
            get {
                return ResourceManager.GetString("Stock_Difference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Taking Date.
        /// </summary>
        internal static string Stock_Taking_Date {
            get {
                return ResourceManager.GetString("Stock_Taking_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Taking No.
        /// </summary>
        internal static string Stock_Taking_No {
            get {
                return ResourceManager.GetString("Stock_Taking_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Taking Report.
        /// </summary>
        internal static string Stock_Taking_Report {
            get {
                return ResourceManager.GetString("Stock_Taking_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stool/Mala.
        /// </summary>
        internal static string Stool_Mala {
            get {
                return ResourceManager.GetString("Stool_Mala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Systalic.
        /// </summary>
        internal static string Systalic {
            get {
                return ResourceManager.GetString("Systalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tariff Category.
        /// </summary>
        internal static string Tariff_Category {
            get {
                return ResourceManager.GetString("Tariff_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tariff Category.
        /// </summary>
        internal static string Tariff_Category1 {
            get {
                return ResourceManager.GetString("Tariff_Category1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax%.
        /// </summary>
        internal static string Tax_ {
            get {
                return ResourceManager.GetString("Tax_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature(°F/°C).
        /// </summary>
        internal static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Description.
        /// </summary>
        internal static string Test_Description {
            get {
                return ResourceManager.GetString("Test_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Description.
        /// </summary>
        internal static string Test_Description1 {
            get {
                return ResourceManager.GetString("Test_Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        internal static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tongue/Jihva.
        /// </summary>
        internal static string Tongue_Jihva {
            get {
                return ResourceManager.GetString("Tongue_Jihva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount.
        /// </summary>
        internal static string Total_Amount {
            get {
                return ResourceManager.GetString("Total_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Qty.
        /// </summary>
        internal static string Total_Qty {
            get {
                return ResourceManager.GetString("Total_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total1 {
            get {
                return ResourceManager.GetString("Total1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town.
        /// </summary>
        internal static string Town {
            get {
                return ResourceManager.GetString("Town", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triglycerides.
        /// </summary>
        internal static string Triglycerides {
            get {
                return ResourceManager.GetString("Triglycerides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UID.
        /// </summary>
        internal static string UID {
            get {
                return ResourceManager.GetString("UID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Purchase Price.
        /// </summary>
        internal static string Unit_Purchase_Price {
            get {
                return ResourceManager.GetString("Unit_Purchase_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        internal static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        internal static string Units1 {
            get {
                return ResourceManager.GetString("Units1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urination/Mut.
        /// </summary>
        internal static string Urination_Mut {
            get {
                return ResourceManager.GetString("Urination_Mut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urine Test.
        /// </summary>
        internal static string Urine_Test {
            get {
                return ResourceManager.GetString("Urine_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urobilinogen.
        /// </summary>
        internal static string Urobilinogen {
            get {
                return ResourceManager.GetString("Urobilinogen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string User_Name {
            get {
                return ResourceManager.GetString("User_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaya.
        /// </summary>
        internal static string Vaya {
            get {
                return ResourceManager.GetString("Vaya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VC.
        /// </summary>
        internal static string VC {
            get {
                return ResourceManager.GetString("VC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Type.
        /// </summary>
        internal static string Visit_Type {
            get {
                return ResourceManager.GetString("Visit_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitals and  Test Results.
        /// </summary>
        internal static string Vitals_and_Test_Results {
            get {
                return ResourceManager.GetString("Vitals_and_Test_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight(kg).
        /// </summary>
        internal static string Weight_kg {
            get {
                return ResourceManager.GetString("Weight_kg", resourceCulture);
            }
        }
    }
}
