//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportLocalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Hindi {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Hindi() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReportLocalization.Hindi", typeof(Hindi).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to गर्भपात.
        /// </summary>
        internal static string Abortions {
            get {
                return ResourceManager.GetString("Abortions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पता.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पता पंक्ति 1.
        /// </summary>
        internal static string Address_Line_1 {
            get {
                return ResourceManager.GetString("Address_Line_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पता पंक्ति 2.
        /// </summary>
        internal static string Address_Line_2 {
            get {
                return ResourceManager.GetString("Address_Line_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to उम्र.
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to शराब.
        /// </summary>
        internal static string Alcohol {
            get {
                return ResourceManager.GetString("Alcohol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to एलर्जी.
        /// </summary>
        internal static string Allergy {
            get {
                return ResourceManager.GetString("Allergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to भूख.
        /// </summary>
        internal static string Appetite_Agn {
            get {
                return ResourceManager.GetString("Appetite_Agn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to क्षेत्र.
        /// </summary>
        internal static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मूल्यांकन एवं देखभाल की योजना.
        /// </summary>
        internal static string Assessment_Plan_of_Care {
            get {
                return ResourceManager.GetString("Assessment_Plan_of_Care", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUHID संख्या.
        /// </summary>
        internal static string AUHID_No {
            get {
                return ResourceManager.GetString("AUHID_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to आयुर्वेदिक आकलन.
        /// </summary>
        internal static string Ayurvedic_Assessment {
            get {
                return ResourceManager.GetString("Ayurvedic_Assessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to बिलीरूबिन.
        /// </summary>
        internal static string Bilirubin {
            get {
                return ResourceManager.GetString("Bilirubin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to बिलिंग जानकारी.
        /// </summary>
        internal static string Billing_Information {
            get {
                return ResourceManager.GetString("Billing_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रक्त.
        /// </summary>
        internal static string Blood {
            get {
                return ResourceManager.GetString("Blood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रक्त समूह.
        /// </summary>
        internal static string Blood_Group {
            get {
                return ResourceManager.GetString("Blood_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रक्त दबाव.
        /// </summary>
        internal static string Blood_Pressure {
            get {
                return ResourceManager.GetString("Blood_Pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to बीएमआई.
        /// </summary>
        internal static string BMI {
            get {
                return ResourceManager.GetString("BMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to तंबाकू चबाना.
        /// </summary>
        internal static string Chew_Tobacco {
            get {
                return ResourceManager.GetString("Chew_Tobacco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मुख्य शिकायतें.
        /// </summary>
        internal static string Chief_Complaints {
            get {
                return ResourceManager.GetString("Chief_Complaints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कोलेस्ट्रॉल.
        /// </summary>
        internal static string Cholesterol {
            get {
                return ResourceManager.GetString("Cholesterol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to चिकित्सालय.
        /// </summary>
        internal static string Clinic {
            get {
                return ResourceManager.GetString("Clinic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सहरुग्ण परिस्थितियां.
        /// </summary>
        internal static string Comorbid_Conditions {
            get {
                return ResourceManager.GetString("Comorbid_Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to संपर्क नहीं.
        /// </summary>
        internal static string Contact_No {
            get {
                return ResourceManager.GetString("Contact_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to देश.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जन्म तिथि.
        /// </summary>
        internal static string Date_of_Birth {
            get {
                return ResourceManager.GetString("Date_of_Birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to दिअलिस्टिक.
        /// </summary>
        internal static string Dialastic {
            get {
                return ResourceManager.GetString("Dialastic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to आहार.
        /// </summary>
        internal static string Diet {
            get {
                return ResourceManager.GetString("Diet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जिला.
        /// </summary>
        internal static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to क्या आप वर्तमान में कॉफी और / या चाय पीते हैं?.
        /// </summary>
        internal static string Do_you_currently_drink_coffe_and_or_tea {
            get {
                return ResourceManager.GetString("Do_you_currently_drink_coffe_and_or_tea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to आप व्यायाम करते हैं?.
        /// </summary>
        internal static string Do_you_exercise {
            get {
                return ResourceManager.GetString("Do_you_exercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to डॉक्टर का नाम.
        /// </summary>
        internal static string Doctor_Name {
            get {
                return ResourceManager.GetString("Doctor_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to दवा इतिहास.
        /// </summary>
        internal static string Drug_History {
            get {
                return ResourceManager.GetString("Drug_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to दवाओं के नुस्खे.
        /// </summary>
        internal static string Drugs_Prescription {
            get {
                return ResourceManager.GetString("Drugs_Prescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ईसीजी.
        /// </summary>
        internal static string ECG {
            get {
                return ResourceManager.GetString("ECG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to शिक्षा.
        /// </summary>
        internal static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ई-मेल.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to परिवार के इतिहास.
        /// </summary>
        internal static string Family_History {
            get {
                return ResourceManager.GetString("Family_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to परिवार नियोजन की विधियों.
        /// </summary>
        internal static string Family_Planning_Methods {
            get {
                return ResourceManager.GetString("Family_Planning_Methods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to फ़ैक्स.
        /// </summary>
        internal static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to एफईवी 1.
        /// </summary>
        internal static string FEV1 {
            get {
                return ResourceManager.GetString("FEV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to एफएचआर.
        /// </summary>
        internal static string FHR {
            get {
                return ResourceManager.GetString("FHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अंतिम आकलन.
        /// </summary>
        internal static string Final_Assessment {
            get {
                return ResourceManager.GetString("Final_Assessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to एफवीसी.
        /// </summary>
        internal static string FVC {
            get {
                return ResourceManager.GetString("FVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to लिंग.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सामान्य.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सामान्य आकलन.
        /// </summary>
        internal static string General_Assessment {
            get {
                return ResourceManager.GetString("General_Assessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ग्लूकोज.
        /// </summary>
        internal static string Glucose {
            get {
                return ResourceManager.GetString("Glucose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जीपी-आकलन.
        /// </summary>
        internal static string GP_Assessment {
            get {
                return ResourceManager.GetString("GP_Assessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ग्राविदा.
        /// </summary>
        internal static string Gravida {
            get {
                return ResourceManager.GetString("Gravida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to एचडीएल कोलेस्ट्रॉल.
        /// </summary>
        internal static string HDL_Cholesterol {
            get {
                return ResourceManager.GetString("HDL_Cholesterol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ऊंचाई (सेंटिमीटर).
        /// </summary>
        internal static string Height_cm {
            get {
                return ResourceManager.GetString("Height_cm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to इतिहास.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मौजूद बीमारी का इतिहास.
        /// </summary>
        internal static string History_of_Present_Illness {
            get {
                return ResourceManager.GetString("History_of_Present_Illness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to घर का फोन.
        /// </summary>
        internal static string Home_Phone {
            get {
                return ResourceManager.GetString("Home_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रति सप्ताह कितनी बार?.
        /// </summary>
        internal static string How_Many_Drinks_Per_Week {
            get {
                return ResourceManager.GetString("How_Many_Drinks_Per_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रति दिन कितने पैक?.
        /// </summary>
        internal static string How_Many_Packs_Per_Day {
            get {
                return ResourceManager.GetString("How_Many_Packs_Per_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रति दिन कितने कप.
        /// </summary>
        internal static string If_is_how_Many_cups_Per_Day {
            get {
                return ResourceManager.GetString("If_is_how_Many_cups_Per_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to यदि छोड़ दिया, तो आपने कब छोड़ा?.
        /// </summary>
        internal static string If_quit_when_did_you_quit {
            get {
                return ResourceManager.GetString("If_quit_when_did_you_quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to यदि हाँ, तो.
        /// </summary>
        internal static string If_yes {
            get {
                return ResourceManager.GetString("If_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to टीकाकरण इतिहास.
        /// </summary>
        internal static string Immunisation_History {
            get {
                return ResourceManager.GetString("Immunisation_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to परीक्षण सलाह.
        /// </summary>
        internal static string Investigations_Advised {
            get {
                return ResourceManager.GetString("Investigations_Advised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कीटोन्स.
        /// </summary>
        internal static string Ketones {
            get {
                return ResourceManager.GetString("Ketones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to एलडीएल कोलेस्ट्रॉल.
        /// </summary>
        internal static string LDL_Cholesterol {
            get {
                return ResourceManager.GetString("LDL_Cholesterol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ल्यूकोसाइट.
        /// </summary>
        internal static string Leucocytes {
            get {
                return ResourceManager.GetString("Leucocytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जहाँ रहते हैं.
        /// </summary>
        internal static string Living {
            get {
                return ResourceManager.GetString("Living", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to एलएमपी.
        /// </summary>
        internal static string LMP {
            get {
                return ResourceManager.GetString("LMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मलेरिया परीक्षण.
        /// </summary>
        internal static string Malaria_Test {
            get {
                return ResourceManager.GetString("Malaria_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to एमएपी.
        /// </summary>
        internal static string MAP {
            get {
                return ResourceManager.GetString("MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to वैवाहिक स्थिति.
        /// </summary>
        internal static string Marital_Status {
            get {
                return ResourceManager.GetString("Marital_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मासिक धर्म इतिहास.
        /// </summary>
        internal static string Menstrual_History {
            get {
                return ResourceManager.GetString("Menstrual_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मोबाइल 1.
        /// </summary>
        internal static string Mobile_1 {
            get {
                return ResourceManager.GetString("Mobile_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मोबाइल 2.
        /// </summary>
        internal static string Mobile_2 {
            get {
                return ResourceManager.GetString("Mobile_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to नाम.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to आधार संख्या.
        /// </summary>
        internal static string National_ID {
            get {
                return ResourceManager.GetString("National_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to राष्ट्रीयता.
        /// </summary>
        internal static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to परिजनों के आगे विवरण.
        /// </summary>
        internal static string Next_To_Kin_Details {
            get {
                return ResourceManager.GetString("Next_To_Kin_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to नाइट्रेट.
        /// </summary>
        internal static string Nitrates {
            get {
                return ResourceManager.GetString("Nitrates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रसूति इतिहास.
        /// </summary>
        internal static string Obstetric_History {
            get {
                return ResourceManager.GetString("Obstetric_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to व्यवसाय.
        /// </summary>
        internal static string Occupation {
            get {
                return ResourceManager.GetString("Occupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to व्यावसायिक इतिहास.
        /// </summary>
        internal static string Occupational_History {
            get {
                return ResourceManager.GetString("Occupational_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कार्यालय फ़ोन.
        /// </summary>
        internal static string Office_Phone {
            get {
                return ResourceManager.GetString("Office_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to बाह्य परामर्श पत्र.
        /// </summary>
        internal static string OP_Consult_Note {
            get {
                return ResourceManager.GetString("OP_Consult_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अन्य.
        /// </summary>
        internal static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to बाहर रोगी परामर्श नोट.
        /// </summary>
        internal static string Out_Patient_Consultation_Note {
            get {
                return ResourceManager.GetString("Out_Patient_Consultation_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to दर्द स्कोर.
        /// </summary>
        internal static string Pain_Score {
            get {
                return ResourceManager.GetString("Pain_Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पैरा.
        /// </summary>
        internal static string Para {
            get {
                return ResourceManager.GetString("Para", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पिछले चिकित्सा के इतिहास.
        /// </summary>
        internal static string Past_Medical_History {
            get {
                return ResourceManager.GetString("Past_Medical_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पिछले शल्य चिकित्सा इतिहास.
        /// </summary>
        internal static string Past_Surgical_History {
            get {
                return ResourceManager.GetString("Past_Surgical_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रोगी पता.
        /// </summary>
        internal static string Patient_Address {
            get {
                return ResourceManager.GetString("Patient_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रोगी श्रेणी.
        /// </summary>
        internal static string Patient_Category {
            get {
                return ResourceManager.GetString("Patient_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रोगी का नाम.
        /// </summary>
        internal static string Patient_Name {
            get {
                return ResourceManager.GetString("Patient_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रोगी पंजीकरण जानकारी.
        /// </summary>
        internal static string Patient_Registration_Infomation {
            get {
                return ResourceManager.GetString("Patient_Registration_Infomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रोगी प्रकार.
        /// </summary>
        internal static string Patient_Type {
            get {
                return ResourceManager.GetString("Patient_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to भुगतान प्रकार.
        /// </summary>
        internal static string Payment_Type {
            get {
                return ResourceManager.GetString("Payment_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पीईएफ़.
        /// </summary>
        internal static string PEF {
            get {
                return ResourceManager.GetString("PEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पीएच.
        /// </summary>
        internal static string PH {
            get {
                return ResourceManager.GetString("PH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पिन कोड.
        /// </summary>
        internal static string Pin_Code {
            get {
                return ResourceManager.GetString("Pin_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to देखभाल की योजना.
        /// </summary>
        internal static string Plan_Of_Care {
            get {
                return ResourceManager.GetString("Plan_Of_Care", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to स्थिति.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to गर्भावस्था परीक्षण.
        /// </summary>
        internal static string Pregnancy_Test {
            get {
                return ResourceManager.GetString("Pregnancy_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to निर्धारित तारीख.
        /// </summary>
        internal static string Prescribed_On {
            get {
                return ResourceManager.GetString("Prescribed_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मुद्रित दिन.
        /// </summary>
        internal static string Printed_on {
            get {
                return ResourceManager.GetString("Printed_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रक्रियाओं का सलाह.
        /// </summary>
        internal static string Procedures_Advised {
            get {
                return ResourceManager.GetString("Procedures_Advised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रोटीन.
        /// </summary>
        internal static string Protein {
            get {
                return ResourceManager.GetString("Protein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्राथमिक आकलन.
        /// </summary>
        internal static string Provisional_Assessment {
            get {
                return ResourceManager.GetString("Provisional_Assessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पल्स / दिल दर.
        /// </summary>
        internal static string Pulse_Heart_Rate {
            get {
                return ResourceManager.GetString("Pulse_Heart_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पल्स / नाडी.
        /// </summary>
        internal static string Pulse_Nadi {
            get {
                return ResourceManager.GetString("Pulse_Nadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अनुपात.
        /// </summary>
        internal static string Ratio {
            get {
                return ResourceManager.GetString("Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to संबंध.
        /// </summary>
        internal static string Relationship {
            get {
                return ResourceManager.GetString("Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to धर्म.
        /// </summary>
        internal static string Religion {
            get {
                return ResourceManager.GetString("Religion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to नींद/निद्रा.
        /// </summary>
        internal static string Sleep_Nidra {
            get {
                return ResourceManager.GetString("Sleep_Nidra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सिगरेट धूम्रपान.
        /// </summary>
        internal static string Smoke_Cigarettes {
            get {
                return ResourceManager.GetString("Smoke_Cigarettes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to धूम्रपान.
        /// </summary>
        internal static string Smoking {
            get {
                return ResourceManager.GetString("Smoking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सामाजिक इतिहास.
        /// </summary>
        internal static string Social_History {
            get {
                return ResourceManager.GetString("Social_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सामाजिक-आर्थिक स्थिति.
        /// </summary>
        internal static string Socioeconomic_Status {
            get {
                return ResourceManager.GetString("Socioeconomic_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to विशिष्ट गुरुत्व.
        /// </summary>
        internal static string Specific_Gravity {
            get {
                return ResourceManager.GetString("Specific_Gravity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to स्पाइरोमीटरी.
        /// </summary>
        internal static string Spirometry {
            get {
                return ResourceManager.GetString("Spirometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to एस पी ओ 2.
        /// </summary>
        internal static string Spo2 {
            get {
                return ResourceManager.GetString("Spo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to राज्य.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to स्टूल/मल.
        /// </summary>
        internal static string Stool_Mala {
            get {
                return ResourceManager.GetString("Stool_Mala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सिस्टोलिक.
        /// </summary>
        internal static string Systalic {
            get {
                return ResourceManager.GetString("Systalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to टैरिफ श्रेणी.
        /// </summary>
        internal static string Tariff_Category {
            get {
                return ResourceManager.GetString("Tariff_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to तापमान (°एफ /°सी).
        /// </summary>
        internal static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कुल.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to शहर.
        /// </summary>
        internal static string Town {
            get {
                return ResourceManager.GetString("Town", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ट्राइग्लिसराइड्स.
        /// </summary>
        internal static string Triglycerides {
            get {
                return ResourceManager.GetString("Triglycerides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to यूआईडी.
        /// </summary>
        internal static string UID {
            get {
                return ResourceManager.GetString("UID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पेशाब /मूत्र.
        /// </summary>
        internal static string Urination_Mut {
            get {
                return ResourceManager.GetString("Urination_Mut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मूत्र परीक्षण.
        /// </summary>
        internal static string Urine_Test {
            get {
                return ResourceManager.GetString("Urine_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to यूरोबायलिनोजेन.
        /// </summary>
        internal static string Urobilinogen {
            get {
                return ResourceManager.GetString("Urobilinogen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to वीसी.
        /// </summary>
        internal static string VC {
            get {
                return ResourceManager.GetString("VC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to नब्ज और परीक्षण के परिणाम.
        /// </summary>
        internal static string Vitals_and_Test_Results {
            get {
                return ResourceManager.GetString("Vitals_and_Test_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to वजन (किलो).
        /// </summary>
        internal static string Weight_kg {
            get {
                return ResourceManager.GetString("Weight_kg", resourceCulture);
            }
        }
    }
}
